# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Self-Sovereign Authentication and Password Management # Title of the site, displayed in browser tabs and SEO titles
email: andre@sentry.co # Public contact email, displayed in the site footer or contact page
description: >- # this means to ignore newlines until "baseurl:"
  Self-Sovereign Authentication and Password Management

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sentry.co" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: "<!--more-->"  #global excerpt separator for the blog posts
permalink: pretty # permalink: This sets the permalink style for your posts/pages. 'pretty' means URLs will be built like /year/month/day/title/
twitter_username: sentrydotco # twitter_username: Your Twitter username. This will be used in the social links section of your site.
github_username:  sentrydotco # github_username: Your GitHub username. This will be used in the social links section of your site.

# Build settings
# theme: minima # ⚠️️ Comment this one out soon, we dont use a theme
plugins:
  - jekyll-feed # This plugin generates an Atom (RSS-like) feed of your Jekyll posts
  - jekyll-paginate # This plugin provides traditional pagination for your Jekyll blog posts
  ##- jekyll-paginate-v2

# Blog
defaults: # Default settings for various aspects of your site
  -
    scope: # Defines the scope for which the default settings apply
      path: "" # an empty string here means all files in the project. This sets the scope to all files.
      type: "posts" # previously `post` in Jekyll 2.2. This specifies the type of documents within the scope.
    values: # Values to apply within the defined scope.
      layout: "blogpost" ## Path to template used for blog-posts, not the blog overview

# Extra
andre: # The following lines define the contact information for André J
 name: André J # Name of the contact person
 email: andre@sentry.co # Email address of the contact person
 web: http://www.twitter.com/eoncodes # Website or social media link of the contact person

# Paginate:
gems: [jekyll-paginate] # This line includes the jekyll-paginate gem which is used for pagination in Jekyll.
paginate: 6 # This line sets the number of posts per page to 6.
paginate_path: "blog/page:num/" ##"page:num"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
